
const P=[
{id:"hashmap",n:"Hash map / set",s:"Hash map",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"You need to answer “have I seen this?” in constant time, or count how often things occur.",
kw:['"seen before"','counting / frequency','"contains duplicate"','anagram','O(1) lookup'],
time:"O(n)",space:"O(n)",
cxnote:"One pass, constant-time lookups. The space is the trade — you're buying time with a table.",
tells:[["Order doesn't matter","If rearranging the input wouldn't change the answer, hashing is safe. If it would, you probably need order-preserving structure."],["The answer needs original indices","Two Sum returns positions, so you can't sort. That single constraint rules out the two-pointer solution people reach for."],["You're counting","Frequency maps are the workhorse — anagrams, top-k precursors, dedupe."]],
traps:[["Nested loops","O(n²). Fine at n=100, dead at n=10⁵ — and the interviewer is waiting for you to drop the inner loop."],["Sort first, then scan","O(n log n), and sorting destroys the original indices. If the answer needs positions, you've thrown them away."],["Two pointers","Requires sorted input. Sorting to enable it costs more than the hash map you skipped."]],
probs:["Two Sum","Contains Duplicate","Valid Anagram","Group Anagrams","Longest Consecutive Sequence"]},

{id:"twoptr",n:"Two pointers",s:"Two ptr",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"The input is sorted or symmetric, so two indices walking inward beat any nested scan.",
kw:['"sorted array"','pair sums','in-place','palindrome','O(1) space'],
time:"O(n)",space:"O(1)",
cxnote:"If you had to sort first, the honest total is O(n log n) — the sort dominates, not the scan.",
tells:[["Input is already sorted","That's free information. Not using it is the mistake."],["The problem asks for O(1) space","Hash map is O(n) space. If they've ruled that out explicitly, they're pointing at two pointers."],["Symmetry","Palindromes, reversals, and container-style problems have two natural ends to walk from."]],
traps:[["Hash map","Works, but O(n) extra space when sorted input gives you O(1). Expect a follow-up asking you to do better."],["Binary search per element","O(n log n) instead of O(n), and duplicate handling gets messy fast."],["Brute force pairs","O(n²) — the sortedness is free information you're refusing to use."]],
probs:["3Sum","Valid Palindrome","Container With Most Water","Trapping Rain Water","Remove Duplicates"]},

{id:"window",n:"Sliding window",s:"Window",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"The answer is a contiguous run, and the boundary can move instead of the range restarting.",
kw:['"subarray"','"substring"','contiguous','"longest / shortest"','"at most k"'],
time:"O(n)",space:"O(k)",
cxnote:"Each element enters and leaves the window at most once — that's why it's linear despite the nested-looking while.",
tells:[["“Subarray” or “substring”, never “subsequence”","Subsequence means you can skip elements. That's DP territory, not a window."],["The word “contiguous”","This is the single loudest keyword on the whole wheel."],["A constraint that can be violated then repaired","“At most k distinct” — expand until invalid, shrink until valid again."]],
traps:[["Check every subarray","O(n²) or O(n³) windows. The whole point is that the window moves instead of restarting."],["Dynamic programming","Overkill — there's no branching subproblem here, just a boundary that slides."],["Prefix sums alone","Fine for fixed-sum queries, but can't express “shrink until valid” constraints like a distinct-character limit."]],
probs:["Longest Substring Without Repeating","Minimum Window Substring","Longest Repeating Character Replacement","Max Consecutive Ones III"]},

{id:"stack",n:"Stack",s:"Stack",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"Order matters and the most recent unresolved item is always the one you need next.",
kw:['matching / nesting','"valid parentheses"','"next greater"','undo','monotonic'],
time:"O(n)",space:"O(n)",
cxnote:"Monotonic stack is linear even though it looks quadratic — each element is pushed once and popped once.",
tells:[["Nesting","Anything that opens and closes. A counter handles one bracket type; a stack handles all three."],["“Next greater / warmer / smaller”","This phrase means monotonic stack almost every time, and it's the least obvious tell on the wheel."],["You need the most recent thing","Not the first, not the largest — the most recent. That's LIFO by definition."]],
traps:[["Counter variable","Works for one bracket type only. Add [ and { and a counter can't tell you which one closed wrong."],["Regex or repeated replace","Repeated replacement is O(n²) and silently fails past shallow nesting."],["Recursion","It IS a stack — just the call stack, with worse space control and a hard depth limit."]],
probs:["Valid Parentheses","Daily Temperatures","Largest Rectangle in Histogram","Min Stack","Evaluate RPN"]},

{id:"traversal",n:"DFS / BFS",s:"DFS/BFS",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"The path itself matters — its length, its existence, or the set of nodes it reaches.",
kw:['grid / matrix','"islands"','tree','"shortest path"','level order'],
time:"O(V+E)",space:"O(V)",
cxnote:"On a grid that's O(rows × cols). BFS space is the widest level; DFS space is the deepest path.",
tells:[["Shortest path on unweighted edges → BFS","Not DFS. DFS finds a path, not the shortest one. This is the most common wrong answer in graph questions."],["“Level order” or “by depth” → BFS","The queue processes one full level before the next."],["“Does a path exist” or “visit everything” → either","When only reachability matters, pick DFS for the shorter code."]],
traps:[["DFS when asked for shortest path","DFS finds a path, not the shortest. On unweighted graphs BFS is correct — this is the classic trap."],["Union-Find","Great for static connectivity, but it can't give you path length or traversal order."],["Dijkstra on an unweighted graph","Correct but wasteful — a heap you don't need. BFS is Dijkstra when every weight is 1."]],
probs:["Number of Islands","Rotting Oranges","Course Schedule","Binary Tree Level Order","Clone Graph"]},

{id:"heap",n:"Heap",s:"Heap",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"You need the extreme element repeatedly, but never the full sorted order.",
kw:['"top k"','"kth largest"','running median','merge k lists','streaming'],
time:"O(n log k)",space:"O(k)",
cxnote:"Keeping the heap at size k is the whole trick. A heap of size n is just a slower sort.",
tells:[["“Top k” where k ≪ n","O(n log k) beats O(n log n) meaningfully when k is 10 and n is a million."],["Input arrives as a stream","You can't sort what hasn't arrived. This is where heap beats quickselect outright."],["Two heaps for a median","Max-heap on the low half, min-heap on the high half. Worth memorising."]],
traps:[["Sort everything","O(n log n) when a size-k heap gives O(n log k). That gap matters when k is 10 and n is a million."],["Quickselect","Better average case for one-shot top-k, but it breaks on streaming input — you can't re-partition data you haven't seen."],["Scan k times","O(nk). At k=1000 you've built an accidental O(n²)."]],
probs:["Kth Largest Element","Top K Frequent Elements","Find Median from Data Stream","Merge K Sorted Lists"]},

{id:"dp",n:"Dynamic programming",s:"DP",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"Choices branch, subproblems repeat, and a greedy pick can be locally right but globally wrong.",
kw:['"number of ways"','"min cost / max value"','subsequence','"can you reach"'],
time:"O(n·k)",space:"O(n) → O(1)",
cxnote:"Space is usually collapsible — if row i only reads row i−1, you need two rows, not the whole table.",
tells:[["“Number of ways” to do something","Counting paths through a decision tree is DP by definition."],["“Subsequence”, not “subarray”","Skipping is allowed, so a window can't express it."],["Greedy has a counterexample","Coin change with [1,3,4] and target 6: greedy takes 4+1+1, the optimum is 3+3. Always test greedy before trusting it."]],
traps:[["Greedy","Feels right, fails on the counterexample. Coin change with [1,3,4] and target 6: greedy takes 4+1+1, the optimum is 3+3."],["Plain recursion","Correct but exponential — the same subproblem recomputed. Memoisation is the only difference between TLE and accepted."],["Sliding window","Only works when the answer is a contiguous range. DP handles skips and branches."]],
probs:["Coin Change","Climbing Stairs","House Robber","Longest Increasing Subsequence","Edit Distance"]},

{id:"backtrack",n:"Backtracking",s:"Backtrack",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"The output is every valid arrangement, not a count and not an optimum.",
kw:['"all combinations"','"all permutations"','N-queens','"return all"'],
time:"O(n!) / O(2ⁿ)",space:"O(n)",
cxnote:"Exponential by nature — you're enumerating the answer set. Space is recursion depth, not output size.",
tells:[["The return type is a list of lists","That single fact rules out DP, which gives you a count or an optimum but never the actual set."],["Constraints prune early","N-queens is 8! in theory but far less in practice, because invalid branches die at depth 2."],["n is small (≤ 20)","Check the constraints. Exponential is only acceptable when the input is tiny — and if it is, that's permission."]],
traps:[["Dynamic programming","DP gives you the count or the optimum, not the actual list. If the output is a list of lists, DP can't produce it."],["Nested loops","Only works when the depth is fixed at write time. k-deep combinations need recursion."],["Bitmask iteration","Fine for subsets of ≤20 items, but it can't prune — you enumerate all 2ⁿ even when most branches die at depth 2."]],
probs:["Permutations","Subsets","Combination Sum","N-Queens","Word Search","Palindrome Partitioning"]},

{id:"binsearch",n:"Binary search",s:"Bin search",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"Something is monotonic — either the array, or the yes/no answer across a range of candidates.",
kw:['sorted + "find"','"O(log n)"','rotated','"minimum such that"','peak'],
time:"O(log n)",space:"O(1)",
cxnote:"Searching an answer space costs O(log(range) × cost of one check) — often O(n log n) overall, still far better than brute force.",
tells:[["The problem states O(log n)","That's not a hint, it's an instruction."],["“Minimum capacity / speed such that…”","Binary search on the answer, not the array. The array might not even be sorted."],["Rotated or partially sorted","Still binary-searchable — one half is always sorted, and you can tell which."]],
traps:[["Linear scan","O(n) when O(log n) is available. If you're searching an answer space up to 10⁹, linear isn't slow — it's impossible."],["Hash map","Can't answer range or “first element ≥ x” queries. Hashing destroys order."],["Sorting first","If the input is already sorted you wasted O(n log n). If it isn't, check whether you're searching the answer space rather than the array."]],
probs:["Binary Search","Search in Rotated Sorted Array","Koko Eating Bananas","Find Minimum in Rotated Array","Median of Two Sorted Arrays"]},

{id:"unionfind",n:"Union-Find",s:"Union-Find",hex:"#C4577F",tint:"#FFFFFF",ink:"#1A1A1A",
blurb:"You're asked whether things belong together, never how far apart they are.",
kw:['"merge accounts"','"number of groups"','cycle detection','"are they connected"'],
time:"O(α(n)) ≈ O(1)",space:"O(n)",
cxnote:"With path compression and union by rank, each operation is inverse-Ackermann — effectively constant.",
tells:[["No distance in the question","If nobody asks how far apart two nodes are, you don't need traversal."],["Edges arrive over time","Union-Find handles incremental merges. BFS would restart from scratch on every new edge."],["Transitive grouping","A~B and B~C must collapse into one group. A single group-by pass can't do that; union-find does it for free."]],
traps:[["BFS/DFS per query","O(V+E) on every query. With q queries that's O(q·(V+E)); union-find answers in near O(1)."],["Adjacency matrix","O(V²) memory and it still needs a traversal to answer connectivity."],["Group by key","Fails on transitive merges — A~B and B~C must collapse into one group, and a single pass won't catch that."]],
probs:["Number of Provinces","Accounts Merge","Redundant Connection","Graph Valid Tree"]}
];

